;; This logfile was generated automatically by `xindy'
;; at 03.09.2018  13:06:24
;; Indexstyle: "/var/folders/7d/0r4hcgsd10xgwww5cs8t8n6m0000gn/T/TfuD4Aj4MR", Rawindex: "/var/folders/7d/0r4hcgsd10xgwww5cs8t8n6m0000gn/T/MfrXAKsltC", Output: "thesis.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "¤Πε" -> "H"
Letter-group: "€»" -> "A"
Letter-group: "—»" -> "E"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€»" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "—»" -> "E"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "¤Πε" -> "H"